# Site settings
baseURL = "https://anastasiafu-portfolio.netlify.app"
languageCode = "en-us"
title = "Anastasia's Portfolio"
theme = "forty"
googleAnalytics = ""
disqusShortname = ""

params:
  banner:
    buttonText: Get Started
    subtitle: |-
     Welcome to my personal website!
    title: Hi, my name is Anastasia
  blog: {}
  contact:
    address:
      - city: London
        country: UK 
        street: Merchant Sqaure
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: afu.mam2023@london.edu
    enable: yes
    phone:
      - phone: 07421 89 8846
        title: Phone
  custom_css: []
  custom_js: []
  description: Description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Anastasia Fu
    enable: yes
    quicklinks:
    social:
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/anastasia.fu.754
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/anastasiaffu/
      - icon: fa-github
        label: GitHub
        url: https://github.com/anaffu
      - icon: fa-linkedin
        label: LinkedIn
        url:https://www.linkedin.com/in/anastasiafu-48bb58171/
  image: ''
  name: Anastaisa Fu
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: lbs.jpg
        subtitle: Find out more about me
        title: About me
        url: blogs/aliquam
      - image: pic02.jpg
        subtitle: Feugiat Amet Tempus
        title: Tempus
        url: blogs/tempus
      - image: pic03.jpg
        subtitle: Lorem Etiam Nullam
        title: Magna
        url: blogs/magna
      - image: pic04.jpg
        subtitle: Nisl Sed Aliquam
        title: Ipsum
        url: blogs/ipsum
      - image: pic05.jpg
        subtitle: Ipsum Dolor Sit Amet
        title: Consequat
        url: blogs/ipsum
      - image: pic06.jpg
        subtitle: Feugiat Amet Tempus
        title: Etiam
        url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
      \r\n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \r\n    Pellentesque
      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
      pellentesque lorem ipsum dolor. \r\n    Nullam et orci eu lorem consequat tincidunt.
      Vivamus et sagittis libero.\r\n    Mauris aliquet magna magna sed nunc rhoncus
      amet pharetra et feugiat tempus."
    title: Massa libero
    url: blogs